### ISSUE TITLE
Can't compile on macOS w/ Xcode 10.2

### ISSUE THREAD

**Issue by taegyunkim** [chipmunk-project/domino-compiler#1]
C++ header <experimental/tuple> is no longer present with Xcode 10.2 release.
https://developer.apple.com/documentation/xcode_release_notes/xcode_10_2_release_notes
Both Aatish and me are facing this issue. 

```shell
In file included from domino.cc:31:
In file included from ./compiler_pass.h:10:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/experimental/tuple:11:2: error: "<experimental/tuple> has been removed. Use <tuple> instead."
#error "<experimental/tuple> has been removed. Use <tuple> instead."
 ^
In file included from domino.cc:31:
./compiler_pass.h:80:23: error: no member named 'experimental' in namespace 'std'
       output_ = std::experimental::apply(partial_fn, args_);
                 ~~~~~^
2 errors generated.
```

I've tried forcing `-std=c++17` but underlying clang library(3.5.0) doesn't seem to be compatible with that. Showing following error. 

```shell
In file included from /Users/taegyunkim/Workspace/clang+llvm-3.5.0-macosx-apple-darwin/include/clang/AST/AST.h:21:
/Users/taegyunkim/Workspace/clang+llvm-3.5.0-macosx-apple-darwin/include/clang/AST/DeclObjC.h:385:16: error: no template named 'const_mem_fun_t' in namespace 'std'
  typedef std::const_mem_fun_t<QualType, ParmVarDecl> deref_fun;
          ~~~~~^
In file included from domino.cc:1:
In file included from ./if_conversion_handler.h:9:
In file included from /Users/taegyunkim/Workspace/clang+llvm-3.5.0-macosx-apple-darwin/include/clang/AST/Decl.h:18:
In file included from /Users/taegyunkim/Workspace/clang+llvm-3.5.0-macosx-apple-darwin/include/clang/AST/DeclBase.h:18:
In file included from /Users/taegyunkim/Workspace/clang+llvm-3.5.0-macosx-apple-darwin/include/clang/AST/DeclarationName.h:17:
In file included from /Users/taegyunkim/Workspace/clang+llvm-3.5.0-macosx-apple-darwin/include/clang/Basic/PartialDiagnostic.h:21:
/Users/taegyunkim/Workspace/clang+llvm-3.5.0-macosx-apple-darwin/include/llvm/ADT/STLExtras.h:211:20: error: type 'int' cannot be used prior to '::' because it has no members
  typedef typename UnaryFunc::result_type value_type;
                   ^
/Users/taegyunkim/Workspace/clang+llvm-3.5.0-macosx-apple-darwin/include/clang/AST/DeclObjC.h:389:23: note: in instantiation of template class 'llvm::mapped_iterator<const clang::ParmVarDecl *const *, int>' requested here
  param_type_iterator param_type_begin() const {
                      ^
/Users/taegyunkim/Workspace/clang+llvm-3.5.0-macosx-apple-darwin/include/clang/AST/DeclObjC.h:390:46: error: functional-style cast from 'clang::QualType (clang::ValueDecl::*)() const' to 'clang::ObjCMethodDecl::deref_fun' (aka 'int') is
      not allowed
    return llvm::map_iterator(param_begin(), deref_fun(&ParmVarDecl::getType));
                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/taegyunkim/Workspace/clang+llvm-3.5.0-macosx-apple-darwin/include/clang/AST/DeclObjC.h:393:44: error: functional-style cast from 'clang::QualType (clang::ValueDecl::*)() const' to 'clang::ObjCMethodDecl::deref_fun' (aka 'int') is
      not allowed
    return llvm::map_iterator(param_end(), deref_fun(&ParmVarDecl::getType));
                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
4 errors generated.
```

We probably need to make this repo and dependency compatible with c++17. I can't think of any other easy way to fix this.
